input_stream: "input_video"

output_stream: "face_detections"

output_stream: "multi_face_landmarks"

output_stream: "multi_face_geometry"

output_stream: "output_video"

max_queue_size: 1

executor {
  type: "ApplicationThreadExecutor"
}


# Defines side packets for further use in the graph.
node {
  calculator: "ConstantSidePacketCalculator"
  output_side_packet: "PACKET:0:num_faces"
  output_side_packet: "PACKET:1:with_attention"
  node_options: {
    [type.googleapis.com/mediapipe.ConstantSidePacketCalculatorOptions]: {
      packet { int_value: 1 }
      packet { bool_value: false }
    }
  }
}

node {
  calculator: "GlScalerCalculator"
  input_stream: "VIDEO:input_video"
  output_stream: "VIDEO:transformed_input_video"
  node_options: {
    [type.googleapis.com/mediapipe.GlScalerCalculatorOptions] {
      scale_mode: FIT
      output_width: 480
      output_height: 720
      flip_horizontal: true
    }
  }
}

# Extracts the input image frame dimensions as a separate packet.
node {
  calculator: "ImagePropertiesCalculator"
  input_stream: "IMAGE_GPU:transformed_input_video"
  output_stream: "SIZE:input_video_size"
}


node {
  calculator: "RenderGPUBufferToCanvasCalculator"
  input_stream: "VIDEO_IN:transformed_input_video"
  output_stream: "VIDEO_OUT:output_video"
}


